local async = require("plenary.async")
async.run(function()
	require("plugins")
	require("maps")
end)
async.run(function()
	require("base")
	require("ui")
end)
async.run(function()
	require("conf")
end)
--vim.notify("Hello Async")
