---@class util
---@field icon Icon

---@class Icon
return {
    Error = '🥵',
    Warn = '🫢',
    Info = '🤔',
    Hint = '👿',
    VirtualText = '🧐',
    LSPFloat = '🤓',
    CodeAction = '🥳',
    comment = {
        Fix = '',
        Debug = '🔧',
        -- Trace = "🤠",
        Todo = '🗒',
        Hack = '✨',
        Perf = '🤯',
        Note = '✔️',
        Test = '💯',
    },
    code_icon = {
        File = '',
        Folder = '',
        Package = '',
        Module = '',
        Namespace = '',
        Macro = '',
        Class = '',
        Constructor = '',
        Field = '',
        Property = '',
        Method = '',
        Struct = '',
        Event = '',
        Interface = '',
        Enum = '',
        EnumMember = '',
        Constant = '',
        Function = '',
        TypeParameter = '',
        Variable = '',
        Operator = '',
        Null = '',
        Boolean = '',
        Number = '',
        String = '',
        Keyword = '',
        Array = '',
        Object = '',
        Text = '',
        Snippet = '',
        Copilot = '',
        -- File = " ",
        -- Module = " ",
        -- Namespace = " ",
        -- Package = " ",
        -- Class = " ",
        -- Method = " ",
        -- Property = " ",
        -- Field = " ",
        -- Constructor = " ",
        -- Enum = " ",
        -- Interface = " ",
        -- Function = " ",
        -- Variable = " ",
        -- Constant = " ",
        -- String = " ",
        -- Number = " ",
        -- Boolean = " ",
        -- Array = " ",
        -- Object = " ",
        -- Key = " ",
        -- Null = " ",
        -- EnumMember = " ",
        -- Struct = " ",
        -- Event = " ",
        -- Operator = " ",
        -- TypeParameter = " ",
    },
}
