---@class util
---@field icon Icon


-- INFO :Code Icon
--vscode = {
--    Text = '  ',
--    Method = '  ',
--    Function = '  ',
--    Constructor = '  ',
--    Field = '  ',
--    Variable = '  ',
--    Class = '  ',
--    Interface = '  ',
--    Module = '  ',
--    Property = '  ',
--    Unit = '  ',
--    Value = '  ',
--    Enum = '  ',
--    Keyword = '  ',
--    Snippet = '  ',
--    Color = '  ',
--    File = '  ',
--    Reference = '  ',
--    Folder = '  ',
--    EnumMember = '  ',
--    Constant = '  ',
--    Struct = '  ',
--    Event = '  ',
--    Operator = '  ',
--    TypeParameter = '  ',
--},
--thin = {
--    File = '',
--    Folder = '',
--    Module = '',
--    Class = '',
--    Constructor = '',
--    Field = '',
--    Property = '',
--    Method = '',
--    Struct = '',
--    Event = '',
--    Interface = '',
--    Enum = '',
--    EnumMember = '',
--    Constant = '',
--    Function = '',
--    TypeParameter = '',
--    Variable = '',
--    Operator = '',
--    Text = '',
--    Snippet = '',
--    Keyword = '',
--},
--other = {
--    Text = '',
--    Method = '',
--    Function = '',
--    Constructor = '',
--    Field = '',
--    Variable = '',
--    Class = 'ﴯ',
--    Interface = '',
--    Module = '',
--    Property = 'ﰠ',
--    Unit = '',
--    Value = '',
--    Enum = '',
--    Keyword = '',
--    Snippet = '',
--    Color = '',
--    File = '',
--    Reference = '',
--    Folder = '',
--    EnumMember = '',
--    Constant = '',
--    Struct = '',
--    Event = '',
--    Operator = '',
--    TypeParameter = '',
--}

---@class Icon
return {
    comment = {
        Fix = '',
        Debug = '🔧',
        -- Trace = "🤠",
        Todo = '🗒',
        Hack = '✨',
        Perf = '🤯',
        Note = '✔️',
        Test = '💯',
    },
    code_icon = {
        Package   = '',
        Namespace = '',
        Macro     = '',
        Null      = '',
        Boolean   = '',
        Number    = '',
        String    = '',
        Array     = '',
        Object    = '',
        Copilot   = '',
        TabNine   = 'ﯓ',


        Text          = '',
        Method        = '',
        Function      = '',
        Constructor   = '',
        Field         = '',
        Variable      = '',
        Class         = 'ﴯ',
        Interface     = '',
        Module        = '',
        Property      = 'ﰠ',
        Unit          = '',
        Value         = '',
        Enum          = '',
        Keyword       = '',
        Snippet       = '',
        Color         = '',
        File          = '',
        Reference     = '',
        Folder        = '',
        EnumMember    = '',
        Constant      = '',
        Struct        = '',
        Event         = '',
        Operator      = '',
        TypeParameter = '',
    },
}
