---@class util
---@field icon Icon

---@class Icon
return {
    comment = {
        Fix = '',
        Debug = '🔧',
        -- Trace = "🤠",
        Todo = '🗒',
        Hack = '✨',
        Perf = '🤯',
        Note = '✔️',
        Test = '💯',
    },
    code_icon = {
        File = '',
        Folder = '',
        Package = '',
        Module = '',
        Namespace = '',
        Macro = '',
        Class = '',
        Constructor = '',
        Field = '',
        Property = '',
        Method = '',
        Struct = '',
        Event = '',
        Interface = '',
        Enum = '',
        EnumMember = '',
        Constant = '',
        Function = '',
        TypeParameter = '',
        Variable = '',
        Operator = '',
        Null = '',
        Boolean = '',
        Number = '',
        String = '',
        Keyword = '',
        Array = '',
        Object = '',
        Text = '',
        Snippet = '',
        Copilot = '',
    },
}
