-- vim.cmd([[hi IncSearch gui=bold guifg=#2f383e guibg=#83c092]])

-- https://zhuanlan.zhihu.com/p/20718108
-- hi 样式名称 guifg=Gvim字体颜色 guibg=Gvim背景颜色 ctermfg=终端Vim字体颜色 ctermbg=终端Vim背景颜色 gui=Gvim字体样式 cterm=终端Vim字体样式
-- hi 的意思是 highlight，也就是它的缩写。 Normal 代表初始化时候的样式，
-- 常规样式， guifg 意思是，在 GVim 中（带有图形界面的Vim） ，字体的颜色是#990808 ，
-- 而 guibg 意思就是 背景色是black黑色，
-- ctermfg 代表了 vim 在 Linux 下的 terminal 终端里的字体配色，
-- terminal 只有 256色， 所以具体， 你需要查询 256 色值表，每个数字具体代表了什么颜色，
-- 而最后的 gui cterm 则是代表了字体的样式，你可以设置为bold(粗体) , 也可以设置为none(常规)

-- 在使用完colorscheme后再使用，若在之前使用，则会被colorscheme覆盖
-- 定义一些高亮组的颜色 see :h highlight
-- vim.cmd([[
--     highlight NonText ctermfg=gray guifg=grey50
--     hi SignColumn ctermbg=None guibg=None
--     hi VertSplit ctermfg=None ctermbg=None cterm=None guibg=None guifg=None
--     ]])

-- TODO: config this color
-- vim.api.nvim_set_hl(0, "NavicIconsFile",          {default = true, link = '@tag'})
-- vim.api.nvim_set_hl(0, "NavicIconsModule",        {default = true, link = '@include'})
-- vim.api.nvim_set_hl(0, "NavicIconsNamespace",     {default = true, link = '@namespace'})
-- vim.api.nvim_set_hl(0, "NavicIconsPackage",       {default = true, link = '@include'})
-- vim.api.nvim_set_hl(0, "NavicIconsClass",         {default = true, link = '@storageclass'})
-- vim.api.nvim_set_hl(0, "NavicIconsMethod",        {default = true, link = '@method'})
-- vim.api.nvim_set_hl(0, "NavicIconsProperty",      {default = true, link = '@property'})
-- vim.api.nvim_set_hl(0, "NavicIconsField",         {default = true, link = '@field'})
-- vim.api.nvim_set_hl(0, "NavicIconsConstructor",   {default = true, link = '@constructor'})
-- vim.api.nvim_set_hl(0, "NavicIconsEnum",          {default = true, link = '@field'})
-- vim.api.nvim_set_hl(0, "NavicIconsInterface",     {default = true, link = '@structure'})
-- vim.api.nvim_set_hl(0, "NavicIconsFunction",      {default = true, link = '@function'})
-- vim.api.nvim_set_hl(0, "NavicIconsVariable",      {default = true, link = '@variable'})
-- vim.api.nvim_set_hl(0, "NavicIconsConstant",      {default = true, link = '@constant'})
-- vim.api.nvim_set_hl(0, "NavicIconsString",        {default = true, link = '@string'})
-- vim.api.nvim_set_hl(0, "NavicIconsNumber",        {default = true, link = '@number'})
-- vim.api.nvim_set_hl(0, "NavicIconsBoolean",       {default = true, link = '@boolean'})
-- vim.api.nvim_set_hl(0, "NavicIconsArray",         {default = true, link = '@type'})
-- vim.api.nvim_set_hl(0, "NavicIconsObject",        {default = true, link = '@structure'})
-- vim.api.nvim_set_hl(0, "NavicIconsKey",           {default = true, link = '@keyword'})
-- vim.api.nvim_set_hl(0, "NavicIconsNull",          {default = true, link = '@tag'})
-- vim.api.nvim_set_hl(0, "NavicIconsEnumMember",    {default = true, link = '@parameter'})
-- vim.api.nvim_set_hl(0, "NavicIconsStruct",        {default = true, link = '@structure'})
-- vim.api.nvim_set_hl(0, "NavicIconsEvent",         {default = true, link = '@label'})
-- vim.api.nvim_set_hl(0, "NavicIconsOperator",      {default = true, link = '@operator'})
-- vim.api.nvim_set_hl(0, "NavicIconsTypeParameter", {default = true, link = '@parameter'})
-- vim.api.nvim_set_hl(0, "NavicText",               {default = true, link = '@function'})
-- vim.api.nvim_set_hl(0, "NavicSeparator",          {default = true, link = '@punctuation'})
